version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
  database:
    container_name: database
    image: postgres:16.3-bookworm
  redis:
    image: redis:latest
    restart: always


    

